name: image
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: amd64
          - os: ubuntu-24.04-arm
            platform: arm64
    name: build-${{ matrix.platform }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build
        uses: docker/build-push-action@32945a339266b759abcbdc89316275140b0fc960 # v6.8.10
        with:
          context: .
          cache-from: ghcr.io/getsentry/uptime-checker:latest
          cache-to: type=inline
          platforms: linux/${{ matrix.platform }}
          tags: uptime-checker:${{ matrix.platform }}
          outputs: type=docker,dest=/tmp/uptime-checker-${{ matrix.platform }}.tar
          push: false

      - name: Upload Image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: uptime-checker-${{ matrix.platform }}
          path: /tmp/uptime-checker-${{ matrix.platform }}.tar

  assemble-uptime-checker-image:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< "$GHCR_TOKEN"
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Download amd64 Image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.2
        with:
          name: uptime-checker-amd64
          path: /tmp

      - name: Load amd64 Image
        run: docker load --input /tmp/uptime-checker-amd64.tar

      - name: Download arm64 Image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.2
        with:
          name: uptime-checker-arm64
          path: /tmp

      - name: Load arm64 Image
        run: docker load --input /tmp/uptime-checker-arm64.tar

      - name: Push to GitHub Container Registry
        run: |
          docker tag uptime-checker:amd64 ghcr.io/getsentry/uptime-checker:${{ github.sha }}-amd64

          docker tag uptime-checker:arm64 ghcr.io/getsentry/uptime-checker:${{ github.sha }}-arm64

          docker manifest create \
            ghcr.io/getsentry/uptime-checker:${{ github.sha }} \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/uptime-checker:${{ github.sha }}

          docker manifest create \
            ghcr.io/getsentry/uptime-checker:latest \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/uptime-checker:latest

          docker manifest create \
            ghcr.io/getsentry/uptime-checker:nightly \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/uptime-checker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/uptime-checker:nightly

  publish-uptime-checker-to-dockerhub:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: [assemble-uptime-checker-image]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - shell: bash
        run: |
          echo "${{ secrets.DOCKER_HUB_RW_TOKEN }}" | docker login --username=sentrybuilder --password-stdin

          # We push 3 tags to Dockerhub:
          # first, the full sha of the commit
          docker buildx imagetools create --tag getsentry/uptime-checker:${GITHUB_SHA} ghcr.io/getsentry/uptime-checker:${{ github.sha }}

          # second, the short sha of the commit
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker buildx imagetools create --tag getsentry/uptime-checker:${SHORT_SHA} ghcr.io/getsentry/uptime-checker:${{ github.sha }}

          # finally, nightly
          docker buildx imagetools create --tag getsentry/uptime-checker:nightly ghcr.io/getsentry/uptime-checker:${{ github.sha }}